issuer: https://accounts.google.com
# approver-bot@mgreau85-chainguard.iam.gserviceaccount.com
subject: "116161268343964034128"

permissions:
  contents: read
  checks: read
  pull_requests: write

repositories:
  - wolfi-os-staging-test

