# Copyright 2026 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

# OS-2854 jbcg.dev publish job: read the staging snapshot.
# export-wolfi-proof-publish@borg-chainguard-dev.iam.gserviceaccount.com
issuer: https://accounts.google.com
subject: "105415554954833304623"

repositories:
  - export-wolfi-proof

permissions:
  contents: read
