# Copyright 2025 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

issuer: https://token.actions.githubusercontent.com
subject_pattern: repo:chainguard-dev/stereo:.*
claim_pattern:
  job_workflow_ref: chainguard-dev/stereo/.github/workflows/version-stream-presubmit.yaml@.*

permissions:
  contents: read
